name: Build and Package (Release Mode)

on:
  workflow_call:
    secrets:
      RELEASE:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libgtk-4-dev build-essential pkg-config rpm

      - name: Set up Rust toolchain
        run: rustup default stable

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Build project in release mode
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Run packaging tasks
        run: cargo make package

      - name: Prepare artifacts for upload
        run: |
          mkdir -p artifacts
          cp target/debian/fin_*.deb artifacts/
          cp target/generate-rpm/fin*.rpm artifacts/
          cp target/fin-*-solus.tar.gz artifacts/
          cp target/fin-*-arch.tar.gz artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/*
