name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_and_package:
    # Call the reusable workflow from your repository.
    # Note: using your default branch "trunk" here.
    uses: hakimjonas/fin/.github/workflows/package-release.yml@trunk
    secrets:
      RELEASE: ${{ secrets.RELEASE }}

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the job has write permission to create releases.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download artifacts that were uploaded in the build_and_package job.
      - name: Download Debian Artifact
        uses: actions/download-artifact@v4
        with:
          name: fin-package-debian

      - name: Download RPM Artifact
        uses: actions/download-artifact@v4
        with:
          name: fin-package-rpm

      - name: Download Solus Artifact
        uses: actions/download-artifact@v4
        with:
          name: fin-package-solus

      - name: Download Arch Artifact
        uses: actions/download-artifact@v4
        with:
          name: fin-package-arch

      - name: Install release dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libcairo2-dev

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/install.sh | sh
        continue-on-error: true

      # Extract the tag name from GITHUB_REF (e.g., "refs/tags/v1.0.0" becomes "v1.0.0")
      - name: Extract tag from GITHUB_REF
        id: extract-tag
        run: |
          tag=$(echo "${GITHUB_REF}" | sed 's/^refs\/tags\///')
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Release using GitHub CLI
        run: |
          gh release create "${{ steps.extract-tag.outputs.tag }}" \
            --title "Release ${{ steps.extract-tag.outputs.tag }}" \
            --notes "Release notes go here"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload Release Artifacts using GitHub CLI
        run: |
          gh release upload "${{ steps.extract-tag.outputs.tag }}" \
          fin_*.deb fin*.rpm fin-package-solus/fin-*-solus.tar.gz fin-package-arch/fin-*-arch.tar.gz

        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Release
        run: |
          gh release publish "${{ steps.extract-tag.outputs.tag }}"
        env:
          GH_TOKEN: ${{ github.token }}



