name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_and_package:
    uses: ./.github/workflows/ci.yml
    secrets:
      RELEASE: ${{ secrets.RELEASE }}

  release:
    needs: build_and_package
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts/

      - name: Reusable Release
        uses: ./.github/workflows/reusable-release.yml
        with:
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}