name: Release

on:
  push:
    branches:
      - release
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build project in release mode
        run: cargo build --release

      - name: Run packaging tasks
        run: cargo make package

      - name: Install GitHub CLI
        id: install-gh-cli
        run: |
          curl -fsSL https://cli.github.com/packages/install.sh | sh
        continue-on-error: true

      - name: Create Release using GitHub CLI
        run: |
          gh release create "${{ github.ref }}" \
            --title "Release ${{ github.ref }}" \
            --notes "Release notes go here"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Artifacts
        run: |
          gh release upload "${{ github.ref }}" \
            target/debian/fin_*.deb \
            target/fin-*-rpm.tar.gz \
            target/fin-*-solus.tar.gz \
            target/fin-*-arch.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        run: |
          gh release publish "${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}