name: CI

on:
  push:
    branches: [ automations ]
  pull_request:
    branches: [ automations ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev

      - name: Build project in release mode
        run: cargo build --release

      - name: Run tests
        run: cargo test

  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          . $HOME/.cargo/env
          rustup update stable
          rustup default stable

      - name: Install dependencies
        run: sudo dnf install -y gtk4-devel

      - name: Build project in release mode
        run: cargo build --release

      - name: Run tests
        run: cargo test

  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          . $HOME/.cargo/env
          rustup update stable
          rustup default stable

      - name: Install dependencies
        run: sudo pacman -S --noconfirm gtk4

      - name: Build project in release mode
        run: cargo build --release

      - name: Run tests
        run: cargo test

  build-solus:
    runs-on: ubuntu-latest
    container:
      image: silkeh/solus:devel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          . $HOME/.cargo/env
          rustup update stable
          rustup default stable

      - name: Install dependencies
        run: sudo eopkg up && sudo eopkg it -y libgtk-4-devel

      - name: Build project in release mode
        run: cargo build --release

      - name: Run tests
        run: cargo test