# File: .github/workflows/test-sync.yml
name: Test Sync

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check Version Format
        id: version
        uses: nowsprinting/check-version-format-action@v4.0.4
        with:
          prefix: 'v'
          version: ${{ github.ref_name }}

      - name: Test Sync Version Action
        if: steps.semver.outputs.valid == 'true'
        uses: ./.github/actions/sync
        with:
          tag: ${{ github.ref_name }}
